# Generated by Django 5.2.6 on 2025-09-28 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_billing_total_alter_billing_appointment_and_more'),
        ('pacient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Запись создана', 'Запись создана'), ('Запись отменена', 'Запись отменена')], max_length=100)),
                ('seen', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pacient_appointment_notifications', to='base.appointment')),
                ('pacient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pacient.pacient')),
            ],
        ),
        migrations.DeleteModel(
            name='Notificaion',
        ),
    ]
