# Generated by Django 5.2.6 on 2025-10-05 23:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacient', '0002_notification_delete_notificaion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='dob',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
