# Generated by Django 5.2.6 on 2025-09-28 17:56

import django.db.models.deletion
import shortuuid.django_fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
        ('pacient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='billing',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_billing', to='base.appointment'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='billing_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='0123456789', length=6, max_length=10, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='billing',
            name='pacient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacient_billing', to='pacient.pacient'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='billing',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
