# Generated by Django 5.2.6 on 2025-10-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_billing_total_alter_billing_appointment_and_more'),
        ('doctor', '0002_alter_doctor_next_appointment_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notificaion',
            new_name='Notification',
        ),
    ]
