# Generated by Django 5.2.6 on 2025-10-05 18:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_rename_notificaion_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='next_appointment_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
